# recovery.conf is a copy of conf/primary.conf intially
#
#   hardcoded confs:
#       archive_mode = off
#


# custom confs here
# -------------------------------
# shared_buffers = 8GB
# maintenance_work_mem = 1GB

# recovery_prefetch = on
# maintenance_io_concurrency = 32
# wal_decode_buffer_size = 32MB
# max_wal_size=10GB

# bgwriter_delay = 10ms
# bgwriter_lru_maxpages = 5000
# bgwriter_lru_multiplier = 10.0

# max_wal_size = 3GB
checkpoint_timeout = 30
